from __future__ import annotations

from html import escape
from pathlib import Path

from .models import MarketEvent


CSS = """
:root { color-scheme: dark; --bg:#090b10; --panel:#11151d; --line:#232a36; --text:#eef2f7; --muted:#8d98a8; --accent:#7ce7c4; }
* { box-sizing:border-box; }
body { margin:0; background:radial-gradient(circle at 20% 0%, #132028 0, var(--bg) 38%); color:var(--text); font:15px/1.55 Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
main { max-width:1180px; margin:0 auto; padding:56px 24px 80px; }
.eyebrow { color:var(--accent); font-size:12px; font-weight:700; letter-spacing:.16em; text-transform:uppercase; }
h1 { font-size:clamp(42px,8vw,84px); line-height:.95; margin:14px 0 18px; letter-spacing:-.055em; }
.lede { max-width:760px; color:#b8c1cf; font-size:18px; }
.metrics { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:12px; margin:34px 0; }
.metric,.card,.empty { background:rgba(17,21,29,.78); border:1px solid var(--line); border-radius:18px; backdrop-filter:blur(14px); }
.metric { padding:18px; }
.metric strong { display:block; font-size:28px; }
.metric span { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.08em; }
.grid { display:grid; gap:14px; }
.card { padding:22px; }
.row { display:flex; align-items:center; justify-content:space-between; gap:16px; }
.badge { display:inline-flex; padding:5px 9px; border:1px solid #334052; border-radius:999px; color:#c7d0dd; font-size:11px; text-transform:uppercase; letter-spacing:.06em; }
.card h2 { margin:14px 0 8px; font-size:22px; }
.meta,.summary { color:var(--muted); }
.summary { margin:10px 0 0; }
a { color:var(--accent); text-decoration:none; }
.evidence { margin-top:14px; padding-top:14px; border-top:1px solid var(--line); display:flex; flex-wrap:wrap; gap:12px; }
.empty { padding:32px; color:var(--muted); }
footer { margin-top:34px; color:#657084; font-size:12px; }
@media (max-width:760px) { .metrics { grid-template-columns:repeat(2,minmax(0,1fr)); } .row { align-items:flex-start; flex-direction:column; } }
"""


def _count(events: list[MarketEvent], value: str) -> int:
    return sum(1 for event in events if event.event_type.value == value)


def render_dashboard(events: list[MarketEvent], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    cards = []
    for event in events:
        official = event.official_evidence[0] if event.official_evidence else None
        evidence_link = (
            f'<a href="{escape(str(official.url))}" target="_blank" rel="noreferrer">official evidence ↗</a>'
            if official else "no official evidence"
        )
        when = event.event_date.date().isoformat() if event.event_date else "date unknown"
        cards.append(
            f"""
            <article class="card">
              <div class="row"><span class="badge">{escape(event.event_type.value.replace('_',' '))}</span><span class="badge">{escape(event.confidence.value)}</span></div>
              <h2>{escape(event.headline)}</h2>
              <div class="meta">{escape(event.vendor)} · {escape(event.product)} · {when}</div>
              <p class="summary">{escape(event.summary[:700])}</p>
              <div class="evidence">{evidence_link}<span class="meta">Tier 1: {len(event.official_evidence)} · Reaction: {len(event.reaction_evidence)} · Supply: {len(event.supply_evidence)}</span></div>
            </article>
            """
        )

    cards_html = "\n".join(cards) if cards else '<div class="empty">No verified market-change events yet. That is a valid result: GapRadar prefers silence to weak evidence.</div>'
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GapRadar</title><style>{CSS}</style></head>
<body><main>
<div class="eyebrow">Market Change Intelligence</div>
<h1>GapRadar</h1>
<p class="lede">Verified shutdowns, pricing shocks and API or policy changes. Facts first; opportunity claims only after the evidence chain is strong enough.</p>
<section class="metrics">
<div class="metric"><strong>{len(events)}</strong><span>verified events</span></div>
<div class="metric"><strong>{_count(events,'shutdown_eol')}</strong><span>shutdown / EOL</span></div>
<div class="metric"><strong>{_count(events,'price_shock')}</strong><span>price shocks</span></div>
<div class="metric"><strong>{_count(events,'api_terms_change')}</strong><span>API / terms</span></div>
</section>
<section class="grid">{cards_html}</section>
<footer>Generated by GapRadar v0.1 · No official first-party source, no verified event.</footer>
</main></body></html>"""
    output.write_text(html, encoding="utf-8")
